apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: cmak-operator
build:
  artifacts:
    - image: eshepelyuk/cmak-operator-cli
  local:
    push: true
profiles:
  - name: local
    activation:
      - command: dev
    portForward:
      - resourceType: Service
        resourceName: cmak
        port: 2181
      - resourceType: Service
        resourceName: cmak
        port: 9000
    deploy:
      helm:
        releases:
          - name: cmak-operator
            chartPath: .
            imageStrategy:
              helm: {}
            artifactOverrides:
              image: eshepelyuk/cmak-operator-cli

