image: registry.newage.io/eshepelyuk/cmak-operator-cli:latest

cmak:
  clustersCommon:
    curatorConfig:
      zkMaxRetry: 100
      baseSleepTimeMs: 100
      maxSleepTimeMs: 1000
    enabled: true
    kafkaVersion: "2.0.0"
    jmxEnabled: false
    jmxSsl: false
    pollConsumers: true
    filterConsumers: false
    logkafkaEnabled: false
    activeOffsetCacheEnabled: true
    displaySizeEnabled: false
    securityProtocol: "PLAINTEXT"
    tuning:
      brokerViewUpdatePeriodSeconds: 30
      clusterManagerThreadPoolSize: 10
      clusterManagerThreadPoolQueueSize: 100
      kafkaCommandThreadPoolSize: 10
      kafkaCommandThreadPoolQueueSize: 100
      logkafkaCommandThreadPoolSize: 10
      logkafkaCommandThreadPoolQueueSize: 100
      logkafkaUpdatePeriodSeconds: 30
      partitionOffsetCacheTimeoutSecs: 5
      brokerViewThreadPoolSize: 10
      brokerViewThreadPoolQueueSize: 1000
      offsetCacheThreadPoolSize: 10
      offsetCacheThreadPoolQueueSize: 1000
      kafkaAdminClientThreadPoolSize: 10
      kafkaAdminClientThreadPoolQueueSize: 1000
      kafkaManagedOffsetMetadataCheckMillis: 30000
      kafkaManagedOffsetGroupCacheSize: 1000000
      kafkaManagedOffsetGroupExpireDays: 7
  
  clusters: 
    - name: "hrzn01-dev"
      curatorConfig:
        zkConnect: "hrzn01-dev-kafka01.nas.local:2181,hrzn01-dev-kafka02.nas.local:2181,hrzn01-dev-kafka03.nas.local:2181"
    - name: "hrzn01-stage"
      curatorConfig:
        zkConnect: "hrzn01-stage-kafka01.hrzn.stage:2181,hrzn01-stage-kafka02.hrzn.stage:2181,hrzn01-stage-kafka03.hrzn.stage:2181"
    - name: "hrzn05-stage"
      curatorConfig:
        zkConnect: "hrzn05-stage-kafka01.hrzn.stage:2181,hrzn05-stage-kafka02.hrzn.stage:2181,hrzn05-stage-kafka03.hrzn.stage:2181"
