{{ if .Values.cmak.clusters }}
{{- $nm := include "cmak.name" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $nm }}-clusters
  labels:
    {{- include "cmak.labels" . | nindent 4 }}
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 180
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: newage-registry
      volumes:
        - name: {{ $nm }}-clusters
          configMap:
            name: {{ $nm }}-clusters
      containers:
        - name: setup
          image: {{ $.Values.image | quote }}
          command: ['python3', './cmak_cluster.py']
          args: 
            - '{{ $nm }}.{{ $.Release.Namespace }}:2181'
            - '/kafka-manager/configs'
            - '/opt/clusters'
          volumeMounts:
            - name: {{ $nm }}-clusters
              mountPath: /opt/clusters
{{ else }}
# .Values.cmak.clusters is empty, no configuration created in ZooKeeper.
{{ end }}
