apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: zk
      port: 2181
      targetPort: zk
      protocol: TCP
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
