name: Build and publish docker image
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build_docker_job:
    name: Build and publish
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: eshepelyuk
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: detect version
        run: echo "::set-env name=CMAK_VERSION::${GITHUB_REF:10}"
      - name: skaffold build
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: build
          tag: ${{ env.CMAK_VERSION }}

