name: Index Helm charts
on:
  push:
    # paths:
    #   - '*.tgz'    
    branches:
      - 'gh-pages'
jobs:
  helm_index:
    name: Helm index
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: |
          ls -la
          cat index.yaml
      - uses: azure/setup-helm@v1
      - name: helm index
        run: helm repo index .
      - run: |
          ls -la
          cat index.yaml
