name: Index Helm charts
on:
  push:
    paths:
      - '*.tgz'
      - '.github/workflows/*.yaml'
    branches:
      - 'gh-pages'
jobs:
  helm_index:
    name: Helm index
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
      - name: generate index
        run: helm repo index .
      - name: publish index
        uses: actions-x/commit@v2
        with:
          files: index.yaml
          message: 'chore: update helm repository index'
          force: true
