name: Index Helm charts
on:
  push:
    # paths:
    #   - '*.tgz'    
    branches:
      - 'gh-pages'
jobs:
  helm_index:
    name: Helm index
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
      - name: helm index
        run: helm repo index .
      - name: push
        uses: actions-x/commit@v2
        with:
          files: index.yaml
          force: true
